lib/puppet/parser/functions/simp_yumrepo_gpgkeys.rb
Attempt at populating default gpg key list with what exists on the
system by default.  If we find we need to copy more keys from the
system later, we can.
SIMP-362 #close Update default simp GPG list
=> (SIMP-362) Update default simp repo GPG key list

manifests/yum.pp
The SIMP GPG URL should be mutable.  Additionally, SIMP-590
specified a bad default url, which this resolves.
SIMP-642 #close Mutable simp gpg url
=> (SIMP-642) Update SIMP GPG URL

spec/acceptance/mcollective_spec.rb
Realized, while reviewing the new docs, that the existing acceptance
test used the same password everywhere and that that was not a good test
of the system since a flaw could have passed through.
Updated all of the passwords to moderately random, but specific,
garbage.
SIMP-828 #comment Updated acceptance tests
=> (SIMP-828) Updated acceptance test

build/pupmod-simp.spec, manifests/nfs/home_client.pp
Updated a bad default for nfs_server in the home_client class, which
otherwise had the potential to render a nil server value, and
break automounting.
SIMP-893 #close
=> (SIMP-893) Fixed nfs_server default in the home_client class.

spec/acceptance/suites/default/01_mcollective_spec.rb
Tests against the 2.8.9 version of MCO and mco-puppet-agent 1.11.1.
SIMP-1335 #close
=> (SIMP-1335) Test CVE-2016-2788 and CVE-2015-7331

CHANGELOG, Gemfile, metadata.json
The Gemfile still referred to the BKR-896 branch of
https://github.com/trevor-vaughan/beaker, which has since been merged
into the upstream project.  This commit modifies the Gemfile to point to
the correct upstream location.
SIMP-1586 #close
=> (SIMP-1586) Fix beaker reference in Gemfile

.fixtures.yml, CHANGELOG, build/rpm_metadata/requires, manifests/rsyslog/stock/log_server.pp, metadata.json
Replaced sysctl::value with augeas 'sysctl' native type.
SIMP-1684 #comment done in simp-simp
SIMP-2247 #close
=> (SIMP-1684) Remove pupmod-simp-sysctl

.fixtures.yml, CHANGELOG, manifests/kmod_blacklist.pp, spec/classes/kmod_blacklist_spec.rb
In order to remove the module_blacklist class from simplib, we forked
the camptocamp/puppet-kmod module. This commit adds a profile to include
the settings that were previously in the manifest from simplib.
SIMP-2238 #close
SIMP-1679 #comment created profile for kmod blacklist settings
=> (SIMP-2238) Create profile using kmod module

spec/acceptance/suites/default/00_yum_spec.rb, spec/acceptance/suites/default/01_mcollective_spec.rb, spec/acceptance/suites/default/03_nfs_spec.rb, spec/acceptance/suites/default/04_rsyslog_spec.rb
The acceptance tests were failing both because the network interfaces
were not being re-enabled and because the SELinux contexts were not
being set properly in the YUM test.
The MCO test is still failing due to our MCO module not handling the AIO
package properly but that's not a problem with running the tests
inherently and will need additional work.
SIMP-2003 #comment Fixed acceptance tests
=> (SIMP-2003) Fixed the acceptance tests

CHANGELOG, files/etc/systemd/system/ctrl-alt-del.target, manifests/admin.pp, manifests/ctrl_alt_del.pp, manifests/server.pp, spec/classes/ctrl_alt_del_spec.rb, templates/etc/systemd/system/ctrl-alt-del-capture.service.erb
This conflicts with the old 'upstart' class but provides full control
over the behavior of ctrl-alt-del in both systemd and upstart
SIMP-2436 #close
=> (SIMP-2436) Control ctrl-alt-del behavior

manifests/server/rsync_shares.pp
This moved the clamav and mcafee virus definitions to the top level of
the rsync environment since they will be shared across all of the
clients.
SIMP-2469 #comment Move clamav and mcafee defs to top
=> (SIMP-2469) Move clamav and mcafee to top

.fixtures.yml, CHANGELOG, build/rpm_metadata/requires, metadata.json
Removed any dangling references or dependencies on ganglia or snmpd.
They will not be distributed with SIMP 6.
SIMP-2498 #close
=> (SIMP-2498) Remove Ganglia and SNMPD

CHANGELOG, manifests/server.pp, spec/classes/server_spec.rb
Removing including of simp::server::* classes from the simp::server
class in favor of including them in the class list in hiera.
SIMP-2495 #close
=> (SIMP-2495) Remove class includes from simp::server

CHANGELOG, manifests/base_apps.pp, manifests/sysctl.pp, spec/classes/sysctl_spec.rb
- Rearranged logic in sysctl and removed the ipv6 catalyst. ipv6 will
now be unmanaged by default.
SIMP-2485 #close
=> (SIMP-2485) Remove ipv6 catalyst

.fixtures.yml, .travis.yml, build/rpm_metadata/requires, manifests/init.pp, manifests/server/ldap.pp, metadata.json, spec/classes/server/ldap_spec.rb
Migrated all 'openldap' calls to 'simp_openldap' to prep for the future
backend change.
SIMP-2427 #comment Updated the 'simp' module
=> (SIMP-2427) Update to use simp_openldap

CHANGELOG, manifests/init.pp
- Modified rsync stunnel logic to add a connection to the rsync server
only if the machine is *not* the rsync server.
SIMP-2578 #close
=> (SIMP-2578) Updated rsync stunnel logic

CHANGELOG, manifests/init.pp, spec/classes/init_spec.rb
This change ensures that filebucketing, if enabled, will either send to
a remote server or will place files in a separate directory on the
local system.
The system now also defaults to disabling filebucketing
SIMP-2682 #close
=> (SIMP-2682) Fix filebucketing

manifests/init.pp
Added the management of ctrl_alt_del to the default configuration
SIMP-2680 #close
=> (SIMP-2680) Enable ctrl_alt_del management

CHANGELOG, lib/puppet/parser/functions/simp_yumrepo_gpgkeys.rb, manifests/yum.pp, spec/classes/yum_spec.rb, spec/functions/simp_yumrepo_gpgkeys_spec.rb
Previously, the simp repo on clients would have the distribution gpg
keys available. This is incorrect.
This commit also adds the new puppet gpg key and removes the old EPEL 5 key.
SIMP-2692 #close
SIMP-2690 #comment puppet gpg key added to simp/simp
=> (SIMP-2692) Remove dist gpgkey from simp repo

manifests/sysctl.pp
Prior to this `simp::sysctl` used a local variable, `$_ipv6`, which held
the value to `net.ipv6.conf.all.disable_ipv6`.  That was confusing,
because the value is whether or not to disable IPv6, the inverse of
expected meaning.  This commit changes the name of the local variable to
`$_disable_ipv6`.
SIMP-2742 #close
=> (SIMP-2742) Clarify sysctl's ipv6 local variables

manifests/yum.pp, spec/classes/yum_spec.rb
This commit extends the rspec-puppet test coverage for `simp::yum`.
=> (SIMP-2765) Extend simp::yum spec test coverage

CHANGELOG, manifests/server/rsync_shares.pp
- Updated apache rsync hosts_allow to $trusted_nets. The previous value
of 127.0.0.1 would not allow apache to rsync if stunnel was disabled.
SIMP-2987 #close
=> (SIMP-2987) Updated apache rysnc hosts_allow

.fixtures.yml, CHANGELOG, manifests/admin.pp, metadata.json, spec/classes/admin_spec.rb
This commit will add `simp::admin::admin_group` as a polkit
administrator.
SIMP-3055 #close
=> (SIMP-3055) Set polkit administrator group

CHANGELOG, manifests/base_apps.pp
simp::base_apps is using 'simp_options::ensure' instead of
'simp_options::package_ensure'
SIMP-3144 #close
=> (SIMP-3144) simp::base_apps uses simp_options global that doesn't exist

CHANGELOG, functions/knockout.pp
- Due to lack of support for knockout_prefix for arrays in older versions
of Puppet, simp::knockout functionality has been moved to
simplib::knockout because multiple modules are using the function.
- A wrapper has been put around simp::knockout for backwards-compatibility
in our code.
SIMP-3302 #added wrapper to simp::knockout
=> (SIMP-3302) Move simp::knockout functionality into simplib

CHANGELOG
Last tagged version was 4.0.0, so all changes after that are for 4.1.0.
=> (SIMP-3372) simp - changelog cleanup as prep for tagging

CHANGELOG, data/common.yaml, data/os/RedHat.yaml
-changed module from nsswitch to simp::nsswitch in
scenarions simp and simp_lite so nsswitch
would be configured correctly according to simp_options.
SIMP-3483 #close
=> (SIMP-3483) SSSD not working in CentOS 6.9

manifests/rc_local.pp, manifests/server.pp, manifests/server/kickstart/runpuppet.pp, manifests/server/yum.pp, manifests/sssd/client.pp, manifests/yum/repo/internet_simp_dependencies.pp
Specific items addressed in this PR:
* several syntax changes, such as multi-lining code blocks
* using correct keywords removed use of the 'inherits' keyword, which should only be used with the old params pattern
* remove variables from private classes, instead refer to the toplevel class
* comments welcome, still testing.
In the future, we need to address the use of 'include' instead of 'require' in many classes of this module. Currently many 'include' statements cannot be replaced by 'require' without creating cyclical dependencies, which may speak to a larger problem with defined types.
SIMP-3512 #close
=> SIMP-3512 changes to pupmod-simp-simp for puppet supported tags

.fixtures.yml
This project is one of the few that does NOT work with concat 4.0.1,
which is the version on the master of puppetlabs-concat.
=> (SIMP-3613) simp: Pin concat to 3.0.0 in .fixtures.yml

CHANGELOG, data/common.yaml
the simp::server::classes array has incorrect merge defaults, which break hiera's auto-casting by turning it into a hash erroneously
SIMP-3626 #close
=> (SIMP-3626) simp::server::classes array has incorrect merge defaults

.gitlab-ci.yml, .travis.yml, CHANGELOG, metadata.json, spec/acceptance/suites/scenario_poss/metadata.yml
Update version in prep for tag and release.
Also, to facilitate the testing required for release:
- Allow same test failures in gitlab as in travis.
- Split out gitlab acceptance tests so they run on
separate runners.
- Add acceptance tests that are not in the default
suite but are important.
- Shorten job names, so more of the name displays on
the gitlab pipeline graph.
SIMP-3826 #comment pupmod-simp-simp version update
=> (SIMP-3826) pupmod-simp-simp: Fix version

CHANGELOG, manifests/sssd/client.pp, metadata.json
SSSD was filtering out the `administrators` group (GID 700) because
sssd.conf's default min_id was set to value of 1000, causing several
hard-to-diagnose problems for various users.  This patch fixes the
problem by dropping the minimum GID to 500.
SIMP-3893 #close
=> (SIMP-3893) Correct default for `min_id` to 500

spec/acceptance/suites/default/00_simp_spec.rb, spec/acceptance/suites/scenario_one_shot/00_simp_spec.rb, spec/acceptance/suites/scenario_poss/00_simp_spec.rb
Fixes to allow acceptance tests to run on servers in FIPS mode.
SIMP-3969 #comment pupmod acceptance test fixes for FIPS
=> (SIMP-3969) pupmod: Acceptance test fixes for FIPS

CHANGELOG, manifests/sysctl.pp, metadata.json, spec/classes/sysctl_spec.rb
- In simp::sysctl, add parameters for net.ipv6.conf.all.accept_source_route
and net.ipv6.conf.default.accept_source_route and set them to 0 by
default.  This satisfies STIG CCI-0000366.
- Small test fixes to allow acceptance tests to run on servers in FIPS mode
SIMP-3969 #comment pupmod-simp-simp update version for FIPS test fixes
SIMP-4048 #close
=> (SIMP-4048) pupmod-simp-simp: Set net.ipv6.conf.all.accept_source_route

.fixtures.yml
file_concat is not used by pupmod-simp-simp or any of its test dependencies
SIMP-4432 #comment simp remove file_concat from fixtures
=> (SIMP-4432) simp: remove file_concat from fixtures

.gitlab-ci.yml, .travis.yml, CHANGELOG, manifests/puppetdb.pp, spec/classes/puppetdb_spec.rb, spec/fixtures/hieradata/simp_puppetdb_manage_config_false.yaml
Set the ownership and permissions of puppet/puppetdb.conf in
simp::puppetdb, instead of allowing them to be set to those of
the process running puppet, if the file needs to be created.
This is part of the fix to the failure of SIMP to bootstrap on a
system on which root's umask has already been restricted to 077.
SIMP-4482 #comment pupmod-simp-simp fix for puppet/puppetdb.conf
=> (SIMP-4482) Set ownership and permissions of puppet/puppetdb.conf

.gitlab-ci.yml, CHANGELOG, manifests/admin.pp, spec/classes/admin_spec.rb, spec/classes/init_spec.rb, spec/classes/server_spec.rb, spec/spec_helper.rb
- Fixed a bug where if the `puppet_settings` fact did not exist, users
in the `%administrators` group could `rm -rf` any path
- The value in the hash was also corrected to
`$facts['puppet_settings']['main']['ssldir']`
SIMP-4441 #close
=> (SIMP-4505) Fix admin_clean_puppet_certs sudo bug

CHANGELOG, metadata.json
- The name for nsswitch module was spelled wrong.
SIMP-4543 #comment updates for pupmod-simp-simp
=> (SIMP-4543) Change log updates (and metadata.json)

.gitlab-ci.yml, CHANGELOG, manifests/prelink.pp, spec/acceptance/suites/default/01_prelink_spec.rb, spec/classes/prelink_spec.rb
The prelink acceptance tests were failing when the server was in
FIPS mode because FIPS and prelink are incompatible!  So, to
prevent an uninformed user from making this mistake, updated
simp::prelink to ensure prelinking is disabled when the server
is in FIPS mode.
SIMP-4579 #close
=> (SIMP-4579) simp: prelink acceptance tests fail in FIPS mode

CHANGELOG, manifests/ctrl_alt_del.pp, metadata.json
- change perms set on service file to prevent annoying errors.
SIMP-4625 #close
SIMP-4597 #comment ctrl-alt-del-capture fix applied
=> (SIMP-4597) Fix Perms on ctrl-alt-del-capture file

CHANGELOG, manifests/server/kickstart/runpuppet.pp, spec/classes/server/kickstart/files/default_runpuppet, spec/classes/server/kickstart/runpuppet_spec.rb
- For EL7, in the runpuppet init script used to bootstrap kickstarted
clients, persist the hostname retrieved by DHCP as a static hostname.
This prevents problems that can arise when the DHCP lease expires
in the middle of the client bootstrap puppet runs.
SIMP-4819 #close
=> (SIMP-4819) Set hostname in runpuppet

CHANGELOG, manifests/server.pp, spec/acceptance/suites/scenario_one_shot/00_simp_spec.rb, spec/acceptance/suites/scenario_remote_access/templates/client_hieradata.yaml.erb, spec/fixtures/hieradata/default.yaml
- removed the check for simp_options::selinux.  The inclussion of
selinux module will rely on the scenario class lists.
SIMP-3858 #comment pupmod-simp-simp updated
SIMP-4529 #close
=> (SIMP-3858) Remove simp_options::selinux

.pmtignore, CHANGELOG, files/var/www/ks/bootstrap_simp_client, spec/unit/bootstrap_simp_client_spec.rb, tests/README, tests/bootstrap_simp_client.rb
Created bootstrap_simp_client script to be used by service scripts.
- Contains the bootstrap actions of existing runpuppet
- As an enhancement, now support exponential backoff on failure
to connect to the Puppet server.
Note: Use of this script and its download during kickstart are
addressed in other tickets.
SIMP-4859 #close
=> (SIMP-4859) Separate runpuppet script from the services

.gitignore, .gitlab-ci.yml, CHANGELOG, Gemfile, data/common.yaml, data/os/windows.yaml, manifests/init.pp, manifests/version.pp, metadata.json, spec/classes/init_spec.rb
* Add conditional on Windows platforms, that changes the simp.version
location depending on whether it was Windows or not.
* Add module data for $facts['puppet_vardir']/simp user, group, and mode
* Add stub data for scenarios, there's no reason to fail a catalog compile
just by including simp.
Fixes enterprise-meta#338
SIMP-4849 #close
=> (SIMP-4849) Add Windows support to the module

CHANGELOG, manifests/admin.pp
This allows the sane defaults in the `sudo` module to take care of
setting the `host_list` parameter on any `sudo::user_specification`
entries.
SIMP-4966 #close
=> (SIMP-4966) Remove explicit 'host_list' calls

CHANGELOG, manifests/server/kickstart.pp, manifests/server/kickstart/runpuppet.pp, manifests/server/kickstart/simp_client_bootstrap.pp, spec/acceptance/suites/no_simp_server/kickstart_spec.rb, spec/classes/server/kickstart_spec.rb
Fixed a usability bug in which simp::server::kickstart did not allow
the bootstrap scripts provided by simp::server::kickstart::runpuppet
and simp::server::kickstart::simp_client_bootstrap to be configured
via hieradata, when those classes were managed by simp::server::kickstart.
SIMP-5213 #close
=> (SIMP-5213) simp::server::kickstart usability bug

metadata.json
Revert from saz/timezone to simp/timezone.  Although using
saz/timezone from here in out makes sense from a Puppet module
perspective, it cannot be done because a design flaw in the
simp-adapter causes RPM upgrade failures.  Instead, we will
pull forward the latest saz/timezone changes into simp/timezone.
We will revert to saz/timezone when we redesign module packaging.
SIMP-5289 #comment revert to simp/timezone in pupmod-simp-simp
=> (SIMP-5289) Revert to simp/timezone

metadata.json
The previous SIMP-5289 PR failed to adjust the
range of simp/timezone dependencies required.
SIMP-5289 #comment fix simp-timezone dep range
=> (SIMP-5289) Fix range of simp/timezone

CHANGELOG, manifests/sysctl.pp, metadata.json, spec/classes/sysctl_spec.rb
- puppetserver was getting error "Not enough space on disk"
when running systemctl which is caused by running out of inotify
user watches.  
- increased fs.inotify.max_user_watchs from 8192 to 65535 to
prevent this.
SIMP-5855 #close
=> (SIMP-5855) Increase max inotify watches

.travis.yml, CHANGELOG, manifests/mountpoints/tmp.pp, manifests/scenario/base.pp, manifests/server/kickstart.pp, manifests/server/ldap.pp, manifests/server/yum.pp, metadata.json, spec/classes/init_spec.rb, spec/classes/scenario/base_spec.rb, spec/classes/server/kickstart_spec.rb, spec/classes/server/ldap_spec.rb, spec/classes/server/yum_spec.rb, templates/etc/httpd/conf.d/ks.conf.erb, templates/etc/httpd/conf.d/yum.conf.erb
- Adjust version to match new parameters added to `simp::root_user` in
an earlier commit
- Use simplib::join_mount_opts() in lieu of join_mount_opts(), a
deprecated simplib Puppet 3 function.
- Use simplib::nets2cidr() in lieu of nets2cidr(), a deprecated
simplib Puppet 3 function.
- Use Puppet's String() in lieu of to_string(), a deprecated simplib
Puppet 3 function.
- Use simp_apache::munge_httpd_networks() in lieu of
munge_httpd_networks(), a deprecated simp_apache Puppet 3 function.
- Use ssh::global_known_hosts() in lieu of ssh_global_known_hosts(),
a deprecated ssh Puppet 3 function.
SIMP-6112 #close
=> (SIMP-6112) Use (namespaced) simplib::join_mount_opts

.fixtures.yml, CHANGELOG, README.md, metadata.json
- Test with latest concat Puppet module instead of 4.1.1
- Test with (newer) pinned versions of Puppet modules:
- postgresql 5.12.1
- puppet_authorization 0.5.0
- Update URLs in the README.md
- Expand the upper bound for the concat and stdlib Puppet modules
in the metadata.json
SIMP-6213 #comment pupmod-simp-simp
=> (SIMP-6213) Use latest concat and others in tests

.fixtures.yml, CHANGELOG, data/os/CentOS.yaml, data/os/OracleLinux.yaml, data/os/RedHat.yaml, metadata.json, spec/classes/init_spec.rb
Added the, inert by default, deferred_resources class so that the
functionality is available via Hiera if desired.
This is particularly relevant to various compliance profiles.
SIMP-5943 #close
=> (SIMP-5943) Add deferred_resources to defaults

.fixtures.yml, CHANGELOG, manifests/puppetdb.pp, metadata.json, spec/classes/puppetdb_spec.rb
- Deprecated simp::puppetdb::read_database_ssl.  Use
simp::puppetdb::read_database_jdbc_ssl_properties which maps
directly to puppetdb::server::read_database_jdbc_ssl_properties
(puppetdb version >= 7.0.0).
- Updated to a minimum puppetdb module version 7.1.0 in the
metadata.json and expanded the upper bound accordingly
- Expanded the upper bound for the concat and stdlib Puppet modules
in the metadata.json
- Updated URLs in the README.md
SIMP-6217 #comment pupmod-simp-simp
=> (SIMP-6217) Update to 7.1.0 puppetdb module

.fixtures.yml, CHANGELOG, metadata.json
- Update to use saz-timezone 5.1.1, instead of temporary simp-timezone
- Clean up ordering of dependencies in the metadata.json
SIMP-4249 #comment pupmod-simp-simp
=> (SIMP-4249) Use saz-timezone 5.1.1

CHANGELOG, functions/yum/repo/sanitize_simp_release_slug.pp, manifests/scenario/base.pp, manifests/version.pp, metadata.json, spec/classes/yum/repo/internet_simp_dependencies_spec.rb, spec/classes/yum/repo/internet_simp_server_spec.rb
- Use simplib::host_is_me in lieu of simplib's Puppet 3 host_is_me
- Use simplib::simp_version in lieu of simplib's Puppet 3 simp_version
SIMP-6317 #close
SIMP-6316 #comment pupmod-simp-simp
=> (SIMP-6317) Use simplib::host_is_me, simplib::simp_version

CHANGELOG, manifests/init.pp, manifests/puppetdb.pp, spec/classes/init_spec.rb
When compiling catalogs in Bolt, the system vardir is on the machine
running Bolt, not the target machine. This caused permission errors.
=> Avoid touching Puppet's vardir in Bolt

.fixtures.yml, .gitlab-ci.yml, .travis.yml, CHANGELOG, functions/yum/repo/sanitize_simp_release_slug.pp, manifests/root_user.pp, metadata.json, spec/classes/yum/repo/internet_simp_dependencies_spec.rb, spec/classes/yum/repo/internet_simp_server_spec.rb, spec/spec_helper.rb
- Fixed a bug where the root password field was attempting to set an 'undef'
value as Sensitive.
- Bumped the supported Puppet version to include Puppet 6
- Removed Puppet 4 from the supported list
SIMP-6339 #close
=> (SIMP-6339) Fix Sensitive value on root password

.gitlab-ci.yml, CHANGELOG, functions/yum/repo/sanitize_simp_release_slug.pp, manifests/mountpoints/tmp.pp, spec/classes/mountpoints/tmp_spec.rb, spec/classes/mountpoints_spec.rb
- Refactor the simp::mountpoints::tmp to use systemd's tmp.mount target if
the system supports systemd.
SIMP-4663 #close
=> (SIMP-4663) Use systemd for tmp.mounts if possible

CHANGELOG, REFERENCE.md, manifests/one_shot/finalize.pp, manifests/puppetdb.pp, manifests/server/yum.pp, manifests/sysctl.pp, spec/classes/puppetdb_spec.rb
- Fixed a bug on el6 systems in which the 'puppetdb-dlo-cleanup' cron
job from the puppetdb module could not be created. Cron rejected this
job because the puppetdb user did not have cron access.
- Added 2 'dead letter office' cleanup configuration parameters to
`simp::puppetdb`
- simp::puppetdb::automatic_dlo_cleanup which maps directly to
puppetdb::automatic_dlo_cleanup
- simp::puppetdb::dlo_max_age which maps directly to puppetdb::dlo_max_age
- Added a few missing '@param' document lines and updated REFERENCE.md
SIMP-6505 #close
=> (SIMP-6505) puppetdb-dlo-cleanup cron resource fails el6

CHANGELOG, manifests/version.pp, metadata.json
- Puppet could not read the /etc/simp/simp.version file because
the world writable permissions set in simp.spec during install
were being overriden.  Change them to world readable, as set in
the install.
-Updated the version of simplib so it calls the simp_version function
which uses Puppet::Util::Execition so it does not crash the system.
SIMP-6506 #close
=> (SIMP-6506) Out of memory Error

data/os/windows.yaml
Fixes: [SIMP-6911](https://simp-project.atlassian.net/browse/SIMP-6911)
Setting `simp::server::data` to an empty array on windows prevents it from being set to `['yum']`.
=> (SIMP-6911) Set simp::server::data to empty array on windows.

CHANGELOG, REFERENCE.md, data/os/CentOS.yaml, data/os/OracleLinux.yaml, data/os/RedHat.yaml, manifests/server.pp, metadata.json
- Remove clamav from the list of classes included by simp in
it scenarios by default.  To manage clamav it should be added
to the class list in hiera.
- The catalyst clamav will be removed from simp_options in future
releases.  It is still here for backwards compatability.
- See the clamav module README for more information on how to use clamav.
SIMP-7113 #close
=> (SIMP-7113) Remove Clamav from default class list.

README.md, REFERENCE.md, manifests/init.pp
This commit fixes minor problems in the markdown docs:
REFERENCE.md:
* Fixes syntax error that derailed all subsequent rendering
* Re-generates REFERENCE.md
README.md:
* Fixes broken syntax for Contribution Guide links
* Fixes note block formatting (broken on GitHub and Puppet Forge)
* Un-muddles note text to make clear what is actually going on
* Moves note to beef up description of `simp::scenario`
=> [SIMP-MAINT] Fix broken docs formatting

CHANGELOG, Gemfile, REFERENCE.md, data/common.yaml, data/os/CentOS-6.yaml, data/os/OracleLinux-6.yaml, data/os/RedHat-6.yaml, manifests/nsswitch.pp, metadata.json, spec/classes/00_classes/nsswitch_spec.rb, spec/unit/compliance_engine/compliance_engine_enforce_spec.rb
- Updated the simp::nsswitch class to have sane defaults
- Added support for mymachines and myhostname by default
- Removed all NIS references since NIS should not be in general usage any
longer and was never natively supported by SIMP
- Configuration files are now common cross all supported OSs since nsswitch
"does the right thing" when it hits a module that it does not recognize
SIMP-7562 #close
=> (SIMP-7562) Update nsswitch options

.fixtures.yml, CHANGELOG, manifests/prelink.pp, spec/classes/00_classes/prelink_spec.rb
* Replace the use of augeasproviders-shellvar with a direct augeas resource
* This was the only location in the SIMP codebase that used it and the
direct Augeas call is trivial
SIMP-7592 #close
=> (SIMP-7592) Remove use of augeasproviders-shellvar

.gitlab-ci.yml, .travis.yml, Gemfile
This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7921 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-simp
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-simp
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
=> (SIMP-7848) Add PE2019.8 to pupmod-simp-simp GL pipeline

.gitlab-ci.yml, .puppet-lint.rc, Gemfile.project
In addition the the normal puppetsync, this change:
* Introduces a repo-specific `Gemfile.project` file to include
`beaker-windows`
* Moves pup6 acceptance tests into matrix level 2
SIMP-8284 #close
[SIMP-7926] #comment Added `Gemfile.project` file to provide `beaker-windows` gem
[SIMP-7855] #comment Updated pupmod-simp-simp
SIMP-8237 #comment Added `--no-parameter_order_check` to pupmod-simp-simp
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
[SIMP-7926]: https://simp-project.atlassian.net/browse/SIMP-7926
=> (SIMP-7855) Update GLCI to test puppet 5.5.20

CHANGELOG, Gemfile, metadata.json, spec/acceptance/suites/default/00_simp_spec.rb, spec/acceptance/suites/netconsole/netconsole_spec.rb
- update the upper bounds for simp module dependencies.  These included
- pupmod
- simp_apache
- correct the version number for chrony module dependency.
- add beaker-windows to the gem file for windows tests.
- netconsole test was rebooting to quickly.  beaker checks
to see that boot time has changed using who -b which is only accurate
to the minute.  Had to put a sleep in to make sure boot time changed.
https://www.rubydoc.info/github/puppetlabs/beaker/Unix%2FExec:reboot
SIMP-8075 #comment updated boundaries simp
=> (SIMP-8075) Update Dependencies for 6.5

CHANGELOG, spec/acceptance/suites/win_client/nodesets/default.yml
- added the host_key option for ssh in the win_client
nodeset.  Openssh has removed ssh-dss as a default in
linux clients in it latest versions and the gitlab runner can
cannot connect to the windows machines without this.
[SIMP-8075] #comment
[SIMP-8075]: https://simp-project.atlassian.net/browse/SIMP-8075
=> (SIMP-8075)simp-simp acceptance tests

CHANGELOG, REFERENCE.md, manifests/mountpoints/proc.pp, metadata.json, spec/acceptance/suites/default/50_mountpoints_spec.rb, spec/classes/00_classes/mountpoints/proc_spec.rb
- Updated simp::mountpoints::proc
- Due to updates to polkit that require being added to the /proc gid group
- Assign a group and gid by default
- Create a group by default
- Discover these values from the system if possible
SIMP-8228 #comment Manage a group for /proc by default
=> (SIMP-8228) Manage a group for /proc by default

CHANGELOG, REFERENCE.md, manifests/yum/repo/local_os_updates.pp, manifests/yum/repo/local_simp.pp, spec/classes/00_classes/yum/repo/local_os_updates_spec.rb, spec/classes/00_classes/yum/repo/local_simp_spec.rb
This patch introduces the new parameters `baseurl` and `gpgkey` to
`simp::yum::repo::local_simp` and `simp::yum::repo::local_os_updates`.
These parameters provide a way to completely override ther respective
yumrepo settings, which makes it possible to host the packages' GPG key
in a non-repo location, as CentOS 8 now requires.
[SIMP-8582] #close
[SIMP-8470] #close
[SIMP-8582]: https://simp-project.atlassian.net/browse/SIMP-8582
[SIMP-8470]: https://simp-project.atlassian.net/browse/SIMP-8470
=> (SIMP-8582) Add params to override default gpgkey

.fixtures.yml, CHANGELOG, Gemfile, REFERENCE.md, functions/yum/repo/baseurl_string.pp, functions/yum/repo/gpgkey_string.pp, manifests/admin.pp, manifests/yum/repo/local_os_updates.pp, manifests/yum/repo/local_simp.pp, metadata.json
Fixed:
- Ensure that the sudoers rule for removing the puppet ssldir is not created
when running from bolt since the directory target is changed at each bolt
run and will result in non-idempotency.
- Un-pinned the firewalld module version in .fixtures.yml because that no
longer appears to cause issues.
- Allow the local yum repos to optionally specify gpgkey or baseurl strings
since, technically, both are optional in the `yumrepo` type if they already
exist on disk.
Workarounds:
- Pinned the rspec-expectations gem to `~> 3.9.0` until rspec-puppet
2.8.0 can be released.
SIMP-8589 #close
=> (SIMP-8589) Fix ssldir sudoers with bolt

CHANGELOG, REFERENCE.md, manifests/admin.pp, metadata.json
Fixed:
- Call `selinux::install` prior to using native types that require the
packages to be installed.
=> (SIMP-8696) Install selinux packages before usage

.gitattributes, .gitignore, .gitlab-ci.yml, .pmtignore, .puppet-lint.rc, CHANGELOG, Gemfile, spec/acceptance/suites/scenario_poss/nodesets/default.yml, spec/classes/01_classes/sssd/client_spec.rb
This patch baselines the latest standardized assets for Puppet modules.
SIMP-9076 #close
[SIMP-8958] #comment Standardized assets in pupmod-simp-simp
[SIMP-8839] #comment Removed EL6 from supported OSes in pupmod-simp-simp
[SIMP-8489] #comment Updated pupmod-simp-simp GLCI pipeline to Puppet 6.18
[SIMP-8923] #comment Renamed 'sanity' to 'releng' in pupmod-simp-simp
[SIMP-8984] #comment Updated pupmod-simp-simp to new GLCI conventions
[SIMP-8958]: https://simp-project.atlassian.net/browse/SIMP-8958
[SIMP-8839]: https://simp-project.atlassian.net/browse/SIMP-8839
[SIMP-8489]: https://simp-project.atlassian.net/browse/SIMP-8489
[SIMP-8923]: https://simp-project.atlassian.net/browse/SIMP-8923
[SIMP-8984]: https://simp-project.atlassian.net/browse/SIMP-8984
=> (SIMP-8958) Standardize assets in pupmod-simp-simp

.github/workflows/pr_glci.yml, .github/workflows/pr_glci_manual.yml, .github/workflows/pr_tests.yml, .gitlab-ci.yml
This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9331] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-simp
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-simp
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …
=> (SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-simp

.fixtures.yml, .gitlab-ci.yml, spec/acceptance/suites/win_client/nodesets/default.yml
This patch updates the Beaker nodesets' Windows boxes, replacing the
(currently 403) opentable/ boxes with boxes from devopsgroup-io/.
[SIMP-9604] #close
[SIMP-9603] #comment upgraded simp/simp to devopsgroup-io box
[SIMP-9604]: https://simp-project.atlassian.net/browse/SIMP-9604
[SIMP-9603]: https://simp-project.atlassian.net/browse/SIMP-9603
=> (SIMP-9603) Switch Windows SUT to devopsgroup-io/

CHANGELOG, manifests/yum/repo/local_simp.pp, spec/acceptance/suites/default/10_yum_spec.rb, spec/classes/00_classes/yum/repo/local_simp_spec.rb
- Update the creation of the /etc/yum.repo.d/simp.repo to OS specific.
SIMP-8488 comment updated pupmod-simp-simp
SIMP-9429 close
=> (SIMP-8488) Update SIMP repo to be OS specific

.fixtures.yml, .github/workflows/pr_tests.yml, .gitlab-ci.yml, CHANGELOG, metadata.json, spec/spec_helper_acceptance.rb
- Removed
- Drop support for Puppet 5
- Changed
- Use puppet/chrony in lieu of aboe/chrony, as VoxPupuli has now assumed
ownership of this module.
- Allow puppetlabs/concat < 8.0.0
- Allow saz/timezone < 7.0.0
- Maintenance
- Update pinned versions of postgresql and puppetdb in .fixtures.yml
- Make sure all fixture URLs end in '.git', as not all private
GitHub mirrors allow shortened URL
- Fail acceptance tests if no examples are executed.
SIMP-9761 #comment pupmod-simp-simp metadata.json updated
SIMP-9666 #comment pupmod-simp-simp_gitlab acceptance tests configured
=> (SIMP-9761) simp/simp Update subset of dependencies

.fixtures.yml, .gitlab-ci.yml, CHANGELOG, data/common.yaml, data/os/CentOS-7.yaml, data/os/OracleLinux-7.yaml, data/os/RedHat-7.yaml, manifests/sssd/client.pp, metadata.json, spec/acceptance/suites/default/files/default_hiera.yaml, spec/acceptance/suites/scenario_one_shot/00_simp_spec.rb, spec/acceptance/suites/scenario_remote_access/00_remote_access_spec.rb, spec/acceptance/suites/scenario_remote_access/nodesets/default.yml, spec/acceptance/suites/scenario_remote_access/nodesets/oel.yml, spec/acceptance/suites/scenario_remote_access/templates/389ds/add_testuser.erb, spec/acceptance/suites/scenario_remote_access/templates/389ds/server_hieradata.yaml.erb, spec/acceptance/suites/scenario_remote_access/templates/client_hieradata.yaml.erb, spec/acceptance/suites/scenario_remote_access/templates/common_hieradata.yaml.erb, spec/acceptance/suites/scenario_remote_access/templates/plain/add_testuser.erb, spec/acceptance/suites/scenario_remote_access/templates/plain/add_testuser_to_admin.erb, spec/acceptance/suites/scenario_remote_access/templates/plain/server_hieradata.yaml.erb, spec/acceptance/suites/win_client/00_default_spec.rb, spec/classes/01_classes/sssd/client_spec.rb, spec/fixtures/hieradata/sssd_domains.yaml, spec/fixtures/hieradata/sssd_domains_nolocal.yaml
- removed LOCAL config from simp::sssd::client and updated
the version of sssd.
- update the version of pupmod-simp-sssd to 7.0 to ensure
the sssd v 1.16 or later is being used so sssd can install
and run without a local provider.
- updated tests that used a ldap server to include tests
against 389ds server.
- remove support for Puppet 5
SIMP-9698 #close
SIMP-9739 #close
SIMP-9737 #comment updated the tests in simp module
=> (SIMP-9698) Remove LOCAL sssd config

.fixtures.yml, CHANGELOG, Gemfile.project, manifests/puppetdb.pp, metadata.json, spec/classes/00_classes/puppetdb_spec.rb, spec/spec_helper.rb
- Added
- simp::puppetdb::disable_update_checking to disable default analytics in
accordance with NIST guidance
SIMP-8813 #close
=> (SIMP-8813) Disable puppetdb analytics

spec/acceptance/nodesets/centos8.yml, spec/acceptance/nodesets/default.yml, spec/acceptance/nodesets/oel.yml, spec/acceptance/nodesets/oel8.yml, spec/acceptance/nodesets/rhel7.yml, spec/acceptance/nodesets/rhel8.yml, spec/acceptance/suites/netconsole/nodesets/centos8.yml, spec/acceptance/suites/no_simp_server/nodesets/centos8.yml, spec/acceptance/suites/scenario_poss/nodesets/default.yml, spec/acceptance/suites/scenario_remote_access/nodesets/default.yml
- update the EL8 nodes in the acceptance tests
to run with generic/centos8 to make sure they using
CentOS 8.4
- update oel7 node to generic box from onyxpoint
- update repos in nodesets to simp-project repos from
packagecloud.
SIMP-10204 #comment update simp
SIMP-10240 #close
=> (SIMP-10204) Ensure testing with CentOS 8.4

CHANGELOG, REFERENCE.md, manifests/puppetdb.pp, manifests/sssd/client.pp
* Added
* PuppetDB now sets UseCodeCacheFlushing by default
* Fixed
* Corrected the HeapDumpOnOutOfMemoryError setting for PuppetDB
SIMP-9756 #close
=> (SIMP-9756) Add UseCodeCacheFlushing for PuppetDB

CHANGELOG, REFERENCE.md, data/common.yaml, manifests/admin.pp, manifests/sudoers.pp, spec/classes/00_classes/admin_spec.rb, spec/classes/00_classes/nsswitch_spec.rb
- Fixed
- Ensure that nsswitch SSSD options for sudoers do not stop on files
- Do not include the auditors sudo user specification if the aliases have not
been included
- Add the following to sudoers defaults
- !visiblepw
- always_set_home
- match_group_by_gid
- always_query_group_plugin
SIMP-10409 #comment simp module fixes found during debugging
=> (SIMP-10409) SSSD and sudoers fixes

CHANGELOG, REFERENCE.md, manifests/yum/repo/local_simp.pp, spec/classes/00_classes/yum/repo/local_simp_spec.rb
- add yum::repo::local_simp::relative_gpg_keys parameter to
point to the relative location of the gpgkeys in the repo.
It defaults to location that simp-gpgkeys installs them,
SIMP/GPGKEYS
SIMP-14000 #close
=> (SIMP-14000) SIMP repo GPGKEYS

CHANGELOG, manifests/sssd/client.pp, spec/classes/01_classes/sssd/client_spec.rb
- Update the sssd configuration to set the ldap schema according to
the type of ldap server. Set the ldap_schema to "rfc2307" for openldap
and to "rfc2307bis" for 389-DS.
The default SIMP configuration and documentation for adding
members to groups is different for 389-DS and openldap.
The default SIMP configuration and documentation for Openldap
uses the attribute "memberUid" and the "cn" of the user.  This is
in general not determinate because more then one user can have
the same "cn".  This is configuration defined in sssd by ldap_schema
rfc2307.
In the new 389-DS server, the SIMP configuration, documentation and
transiton script, use the configuration defined in sssd as rfc2307bis.
This used the attribute "member" and the "dn" of the user.  The
"dn" of the user must be unique in the …
=> (SIMP-10429)  SSSD set schema for ldap provider

CHANGELOG, metadata.json, spec/classes/00_classes/ctrl_alt_del_spec.rb, spec/classes/10_classes/server/kickstart/files/default_simp_client_bootstrap, spec/classes/10_classes/server/kickstart/files/simp_client_bootstrap_with_ntp_servers, spec/classes/10_classes/server/kickstart/files/simp_client_bootstrap_without_print_stats, spec/classes/10_classes/server/kickstart/files/simp_client_bootstrap_without_reboot_on_failure, spec/classes/10_classes/server/kickstart/files/simp_client_bootstrap_without_wait_for_cert, templates/www/ks/simp_client_bootstrap.erb
* Upstart is not supported on any of our supported operating systems and
should have been removed in the past.
Closes #282
=> Remove Upstart

CHANGELOG, metadata.json, spec/spec_helper_acceptance.rb
* Allow `puppet/chrony` < `3.0.0`
* Allow `puppetlabs/stdlib` < `9.0.0`
Closes #284
=> Update Chrony Version

.github/workflows/pr_glci.yml, .github/workflows/pr_tests.yml, .github/workflows/tag_deploy.yml, .gitlab-ci.yml, Gemfile, spec/acceptance/nodesets/oel.yml, spec/acceptance/nodesets/oel8.yml, spec/acceptance/suites/netconsole/nodesets/oel7.yml, spec/acceptance/suites/netconsole/nodesets/oel8.yml, spec/acceptance/suites/no_simp_server/nodesets/oel7.yml, spec/acceptance/suites/no_simp_server/nodesets/oel8.yml, spec/acceptance/suites/scenario_poss/nodesets/default.yml, spec/acceptance/suites/scenario_poss/nodesets/oel8.yml, spec/acceptance/suites/scenario_remote_access/nodesets/oel.yml, spec/acceptance/suites/win_client/nodesets/default.yml
This patch moves puppet 6 refs to 7, puppet 7 refs to 8. Then we manually
update all spec nodesets to point to sicura oel boxes and comment out all 
pup8 tests.
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
=> Removes puppet 6 from .gitlab-ci.yml

.github/workflows/pr_tests.yml, .github/workflows/tag_deploy.yml, .gitlab-ci.yml, .puppet-lint.rc, CHANGELOG, Gemfile, README.md, REFERENCE.md, manifests/admin.pp, manifests/init.pp, manifests/yum/repo/local_os_updates.pp, manifests/yum/repo/local_simp.pp, metadata.json, spec/classes/00_classes/puppetdb_spec.rb, spec/facter/simp_rsync_environments_spec.rb
This patch adds support for RockyLinux 8
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
=> Add RockyLinux 8 support

CHANGELOG, REFERENCE.md, manifests/kmod_blacklist.pp, metadata.json, spec/classes/00_classes/kmod_blacklist_spec.rb
=> (#issue_318) Added ability for users to switch between '/bin/true' and '/bin/false' when disabling kernel modules via the kmod_blacklist class
