simp/pupmod-simp-simp

- build/pupmod-simp.spec
- manifests/nfs/home_client.pp
- spec/classes/nfs/home_client_spec.rb
Ensure 'on' if a remote nfs server is used for home directories.
SIMP-124 #close Set use_nfs_home_dirs
> (SIMP-124) Set selbool use_nfs_home_dirs.

- build/pupmod-simp.spec
- templates/www/ks/runpuppet.erb
A full relabel needs to happen before selinux is fully enabled.
SIMP-401 #comment Run fixfiles
> (SIMP-401) Run fixfiles before final runpuppet runs.

- build/pupmod-simp.spec
- manifests/kickstart_server.pp
- templates/www/ks/runpuppet.erb
> (SIMP-458) Set keylength to 2048 in runpuppet if FIPS mode is enabled.

- manifests/kickstart_server.pp
- templates/www/ks/runpuppet.erb
Keylength was not being set properly.
SIMP-501 #close Fix keylength logic in runpuppet.
> (SIMP-501) Fix keylength logic in runpuppet.

- build/pupmod-simp.spec
- manifests/puppetdb.pp
Updated defaults to conform with updated puppetdb module.
SIMP-536 #close Update simp puppetdb
> (SIMP-536) Update simp puppetdb class defaults.

- manifests/yum.pp
SIMP-642 #comment minor fix: lint error that was failing Travis tests
> (SIMP-642) Fix lint error

- .fixtures.yml
- build/pupmod-simp.spec
- manifests/admin.pp
- manifests/init.pp
- manifests/nfs/export_home.pp
- manifests/rsyslog/stock.pp
- manifests/rsyslog/stock/log_server.pp
- manifests/rsyslog/stock/log_server/forward.pp
- manifests/server.pp
- manifests/server/rsync_shares.pp
- manifests/sssd/client.pp
- manifests/yum.pp
- metadata.json
Enabling simp module for compliance checking
SIMP-720 #comment
> (SIMP-720) Map 800-53 requirements to hiera

- .fixtures.yml
- CHANGELOG
- manifests/nfs/export_home.pp
- metadata.json
- Fixed a data type in export home
- Updated fixtures to reference remote nfs instead of local
SIMP-1325 #close
> (SIMP-1325) Fixed some cruft

- CHANGELOG
- build/rpm_metadata/requires
- metadata.json
> (SIMP-2024) Update iptables dep version

- CHANGELOG
- build/rpm_metadata/requires
- metadata.json
> (SIMP-2033) Fix openldap dependency version

- spec/acceptance/suites/default/05_mountpoints_spec.rb
auditd::add_rules has been changed to auditd::rule
SIMP-2437 #comment update to comment in test
> (SIMP-2437) Change comment to reflect new auditd

- .fixtures.yml
- CHANGELOG
- manifests/admin.pp
- manifests/server.pp
- spec/classes/admin_spec.rb
- spec/classes/server_spec.rb
- spec/classes/sudoers_spec.rb
- spec/fixtures/hieradata/default.yaml
- spec/fixtures/hieradata/puppet_server.yaml
- Beefed up simp::server class to include more default classes
SIMP-2510 #close
> (SIMP-2510) Beef up simp::server

- CHANGELOG
- manifests/init.pp
- spec/classes/init_spec.rb
> (SIMP-2541) Enable $rsync_stunnel by default

- CHANGELOG
- lib/puppet/parser/functions/simp_yumrepo_gpgkeys.rb
- spec/functions/simp_yumrepo_gpgkeys_spec.rb
The Grafana GPG key has been updated in the generation function
SIMP-2818 #close
> (SIMP-2818) Added support for new Grafana GPG Key

- .travis.yml
- CHANGELOG
- manifests/scenario/base.pp
- manifests/scenario/simp.pp
- changed fips to unconditional and moved it to simp scenario
SIMP-2844  #comment  simp modules updated
SIMP-2907  #close
> (SIMP-2844) Changing fips to false not unsetting fips

- spec/acceptance/suites/scenario_remote_access/00_remote_access_spec.rb
> (SIMP-3408) scenario_remote_access test tries to copy wrong file

- CHANGELOG
- build/rpm_metadata/requires
- metadata.json
Add missing kmod dependency to metadata.json and
build/rpm_metadata/requires.
SIMP-3579 #close
> (SIMP-3579) simp: Add kmod dependencies

- .fixtures.yml
> (SIMP-3606) Update timezone URL in fixtures

- .fixtures.yml
- CHANGELOG
- metadata.json
- spec/classes/init_spec.rb
Missed this in earlier releases
> (SIMP-3748) Added 'timezone' to metadata.json

- CHANGELOG
- data/os/RedHat.yaml
- manifests/prelink.pp
- metadata.json
- spec/acceptance/suites/default/01_prelink_spec.rb
- spec/classes/init_spec.rb
- spec/classes/prelink_spec.rb
- spec/classes/server_spec.rb
SIMP-4217 #close prelink classes in pupmod-simp-simp
SIMP-4219 #close prelink class acceptance tests
> (SIMP-4217) Remove prelink if it is not enabled

- CHANGELOG
- metadata.json
SIMP-4401 #comment pupmod-simp-simp remove OBE puppetlabs/inifile dep
> (SIMP-4401) Remove unnecessary puppetlabs/inifile dep

- CHANGELOG
- manifests/root_user.pp
Workaround for https://tickets.puppetlabs.com/browse/PUP-8470
SIMP-4446 #close
> (SIMP-4446) Remove group management for root user

- CHANGELOG
- manifests/nsswitch.pp
- metadata.json
- added trinklin/nsswitch dependancy to metadata.json
SIMP-4430 #close
SIMP-4524 #close
SIMP-4525 #close
> (SIMP-4430) Add nsswitch dependency to metadata

- CHANGELOG
- manifests/rc_local.pp
- spec/classes/rc_local_spec.rb
Changed the mode and added unit test.
SIMP-4776 #close
SIMP-4777 #close
> (SIMP-4776) Change mode of rc.local to 750

- .fixtures.yml
- .gitlab-ci.yml
- Gemfile
- manifests/init.pp
- manifests/scenario/base.pp
- spec/acceptance/nodesets/default.yml
- spec/classes/init_spec.rb
- spec/classes/server/kickstart/runpuppet_spec.rb
- spec/classes/server/kickstart/simp_client_bootstrap_spec.rb
- spec/classes/server/kickstart_spec.rb
- spec/spec_helper.rb
* Update systemd dependency
* Workarounds for server_facts
* Remove travis gem
Content taken from closed PR https://github.com/simp/pupmod-simp-simp/pull/154
> (SIMP-MAINT) Fix tests

- .fixtures.yml
- Rakefile
- spec/classes/puppetdb_spec.rb
- Add missing simp_banners fixture
- Add missing vox_selinux fixture
- Fix spec test bug caused by a bad facts merge
SIMP-5086#comment pupmod-simp-simp fixture fix
> (SIMP-5086) Fix broken tests

- .fixtures.yml
- .gitlab-ci.yml
- CHANGELOG
- hiera.yaml
- metadata.json
- spec/classes/nsswitch_spec.rb
- Update to Hiera 5
- Go back to using saz/timezone, as it supports Hiera 5
- Use latest trlinkin/nsswitch
SIMP-2791 #comment pupmod-simp-simp
SIMP-4887 #comment pupmod-simp-simp
SIMP-5331 #comment pupmod-simp-simp
> (SIMP-2791) Update to Hiera 5

- metadata.json
SIMP-5360 #comment fix missing tlog dep in simp
> (SIMP-5360) Add pupmod-simp-tlog dependency

- .gitlab-ci.yml
- .travis.yml
- Gemfile
- spec/acceptance/nodesets/oel.yml
SIMP-5585 #comment Added pup5 test assets to simp
> (SIMP-5585) Test assets support Puppet 5

- functions/yum/repo/gpgkeys/simp.pp
- manifests/yum/repo/internet_simp_dependencies.pp
- manifests/yum/repo/internet_simp_server.pp
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/scenario_poss/nodesets/default.yml
- spec/acceptance/suites/scenario_poss/nodesets/puppet5.yml
- spec/classes/yum/repo/local_simp_spec.rb
> (SIMP-5751) Update to add SIMP-6 Release Key

- .gitlab-ci.yml
- CHANGELOG
- metadata.json
* Removed unused items
* Added items in the classes list
SIMP-5762 #close
> (SIMP-5762) Update metadata dependency list

- CHANGELOG
- files/scenarios/one_shot/simp_one_shot_finalize.sh
- manifests/one_shot.pp
- manifests/one_shot/finalize.pp
- spec/acceptance/suites/scenario_one_shot/00_simp_spec.rb
- spec/acceptance/suites/scenario_one_shot/metadata.yml
- spec/acceptance/suites/scenario_poss/metadata.yml
* Updated the one_shot scenario tests to function properly
* Removed scenario_one_shot and scenario_poss from running as default
acceptance tests to reduce redundancy in Gitlab
SIMP-6109 #close
> (SIMP-6109) Fix the one_shot scenario tests

- CHANGELOG
- manifests/sysctl.pp
Correct oversight of net.ipv6.conf.all.accept_ra in simp::sysctl.
SIMP-6241 #close
> (SIMP-6241) Manage net.ipv6.conf.all.accept_ra

- spec/acceptance/suites/default/00_simp_spec.rb
- spec/acceptance/suites/default/01_prelink_spec.rb
- spec/acceptance/suites/default/05_shell_logger_spec.rb
- spec/acceptance/suites/default/10_yum_spec.rb
- spec/acceptance/suites/default/20_server_rsync_shares_spec.rb
- spec/acceptance/suites/default/40_sysctl_spec.rb
- spec/acceptance/suites/default/99_kmod_blacklist_spec.rb
- spec/acceptance/suites/default/files/default_hiera.yaml
> (SIMP-MAINT) Clean up tests

- CHANGELOG
- manifests/yum/repo/internet_simp_dependencies.pp
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/scenario_poss/nodesets/default.yml
Updated the URLs to the EPEL GPG keys. The URLs have changed.
SIMP-6709 #close
> (SIMP-6709) EPEL GPG key URLs incorrect

- CHANGELOG
- data/os/windows.yaml
Fixes: [SIMP-6913](https://simp-project.atlassian.net/browse/SIMP-6913)
> (SIMP-6913) Exclude yum from simp::classes for Windows.

- .fixtures.yml
- .gitlab-ci.yml
- Use correct branch for puppet-systemd in fixtures
- Reinstate missing acceptance tests in GitLab
SIMP-6949 #comment pupmod-simp-simp
SIMP-6963 #close
> (SIMP-6949) Fixtures pinned to wrong puppet-systemd branch

- CHANGELOG
- data/common.yaml
- data/os/CentOS-6.yaml
- data/os/OracleLinux-6.yaml
- data/os/RedHat-6.yaml
- manifests/nsswitch.pp
- spec/classes/00_classes/nsswitch_spec.rb
> (SIMP-6638) Allow nsswitch overrides

- CHANGELOG
- manifests/base_apps.pp
- spec/acceptance/suites/base_apps/base_spec.rb
- spec/classes/00_classes/base_apps_spec.rb
- Removed optional appilcations from simp::base_apps for wider OS compatibility
- simp::base_apps::manage_elinks_config no longer has any effect
SIMP-7199 #close
> (SIMP-7199) Clean up simp::base_apps

- .rspec
- CHANGELOG
- REFERENCE.md
- manifests/admin.pp
- manifests/base_apps.pp
- manifests/ctrl_alt_del.pp
- manifests/kmod_blacklist.pp
- manifests/mountpoints.pp
- manifests/mountpoints/tmp.pp
- manifests/netconsole.pp
- manifests/one_shot.pp
- manifests/server/ldap.pp
- manifests/sssd/client.pp
- manifests/sysctl.pp
- spec/classes/00_classes/base_apps_spec.rb
- spec/classes/00_classes/kmod_blacklist_spec.rb
- spec/classes/10_classes/server/ldap_spec.rb
- spec/functions/yum/repo/gpgkeys/os_updates_spec.rb
- spec/rspec_formatters/profile_json.rb
- Finish removing EL6 components
- Ensure that netconsole-service is installed on EL8+
- Added a JSON formatted profiling formatter for rspec
SIMP-8888 #close
SIMP-9132 #close
SIMP-9113 #close
> (SIMP-8888) Complete EL6 removal

- CHANGELOG
- manifests/admin.pp
- spec/classes/00_classes/admin_spec.rb
> (SIMP-9628) Added sudoers options for auditors and admins

- .fixtures.yml
- CHANGELOG
- metadata.json
Migrated from camptocamp/kmod to puppet/kmod
[SIMP-10286] #close
[SIMP-10286]: https://simp-project.atlassian.net/browse/SIMP-10286
> (SIMP-10061) Migrate to puppet/kmod

- CHANGELOG
- manifests/pam_limits/max_logins.pp
> (SIMP-10372) Support all values for maxlogins

- .gitlab-ci.yml
- spec/acceptance/nodesets/default.yml
* Moved windows tests to level 2 to save resources
SIMP-10059 #close
> (SIMP-9970) Add Puppet 7 acceptance tests

- CHANGELOG
- functions/yum/repo/gpgkeys/simp.pp
- spec/classes/00_classes/yum/repo/local_simp_spec.rb
- add the puppet6 key into the list of keys for the simp 6 repo.
SIMP-10400 #close
> (SIMP-10400) Update Keys for local simp repo

- CHANGELOG
- manifests/yum/repo/local_simp.pp
- metadata.json
> (#288) Removed the epel-modular repo from local_simp.pp

- CHANGELOG
- functions/yum/repo/gpgkeys/simp.pp
- metadata.json
> (#292) Removed old GPGKEYS that no longer exist

- spec/classes/00_classes/yum/repo/local_simp_spec.rb
> (#292) Updated spec tests to reflect the removed gpg keys

- CHANGELOG
- Gemfile
- manifests/server.pp
- metadata.json
- spec/classes/10_classes/server_spec.rb
> (#297) Stopped managing nsswitch if authselect is used

- .github/workflows/tag_deploy.yml
- CHANGELOG
- manifests/server.pp
- metadata.json
> (#299) Fixed a bug in the conditional authselect logic

- data/os/Rocky-8.yaml
- data/os/Rocky.yaml
- functions/yum/repo/gpgkeys/os_updates.pp
- functions/yum/repo/gpgkeys/simp.pp
- spec/classes/00_classes/yum/repo/local_os_updates_spec.rb
- spec/classes/00_classes/yum/repo/local_simp_spec.rb
- spec/functions/yum/repo/gpgkeys/os_updates_spec.rb
> (#302) Adding hieradata/test support for Rocky 8

- CHANGELOG
- data/os/AlmaLinux-8.yaml
- data/os/AlmaLinux.yaml
- functions/yum/repo/gpgkeys/simp.pp
- manifests/init.pp
- manifests/server.pp
- metadata.json
- spec/classes/00_classes/yum/repo/local_os_updates_spec.rb
- spec/classes/00_classes/yum/repo/local_simp_spec.rb
* Add support for stdlib 9
* Update other Puppet module dependencies
* Add support for Puppet 8
* Drop support for Puppet 6
> Add AlmaLinux 8 support
